#服务端口
server:
  port: 8090
##项目contextPath
#  servlet:
#    context-path: /******

#tomcat最大线程数，默认为200
  tomcat:
    max-threads: 200
#tomcat的URI编码
    uri-encoding: UTF-8

##数据库连接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helloboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Lu123456@
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
#######################以下为druid增加的配置########################
    type: com.alibaba.druid.pool.DruidDataSource
# 下面为连接池的补充设置，应用到上面所有数据源中
# 初始化大小，最小，最大\
    initialSize: 1
    minIdle: 5
    maxActive: 20
# 配置获取连接等待超时的时间
    maxWait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# 合并多个DruidDataSource的监控数据
#spring.datasource.useGlobalDataSourceStat=true
###################以上为配置druid添加的配置########################

###################以下为jpa增加的配置###########################
  jpa:
    # 配置 DBMS 类型
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # 配置是否将执行的 SQL 输出到日志
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          # 配置开启自动更新表结构
          auto: update
###################以上为配置jpa添加的配置########################

###################以下为redis增加的配置###########################
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
###################以上为配置redis添加的配置########################

###################以下为thymeleaf增加的配置###########################
  # thymeleaf的配置是为了去掉html的校验
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
###################以上为配置thymeleaf添加的配置########################

###################以下为servlet增加的配置###########################
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
###################以上为配置servlet添加的配置########################

###################以下为Actuator 监控增加的配置###########################
info:
  app:
    name: helloboot-actuator
    version: 1.0.0
    test: test
management:
  endpoints:
    web:
      # 打开所有的监控点
      exposure:
        include: '*'
#       代表启用单独的url地址来监控 Spring Boot 应用，为了安全一般都启用独立的端口来访问后端的监控信息
#      base-path: /manage
  endpoint:
    health:
      show-details: always
    # 启用接口关闭 Spring Boot
    shutdown:
      enabled: true
###################以上为配置Actuator 监控添加的配置########################